# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzurePipeline to Harry@brynroad.uk'
    subscriptionId: 'ba0df48e-084c-442a-a503-887bb56b3aae'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzurePipeline'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/HarryBrynLin/RemoteRepoTest/main/CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName azurepipe -fileShareName brynfileshare'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineLatest'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
